baseurl = "https://mspurr.github.io/simontest/"
title = "Copenhagen air pollution"
author = "Emil Deshasta"
paginate = 3
theme = "arabica"

[params]
    description = "Where is it most sustainable to live in Copenhagen"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "example"
    facebook = "example"

[markup.goldmark.renderer]
  unsafe = true
